// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMRpa1U3H1jyVGTQ8IMXzPTskL33YzEk',
    appId: '1:876191657794:web:dd10ebefb1d50a982ee2db',
    messagingSenderId: '876191657794',
    projectId: 'kyafeease',
    authDomain: 'kyafeease.firebaseapp.com',
    storageBucket: 'kyafeease.appspot.com',
    measurementId: 'G-D0E9Z9YELR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYsegZ-IEZCli5YFh8Y8NfU6mRJQAzN44',
    appId: '1:876191657794:android:84e9806ea70a7f112ee2db',
    messagingSenderId: '876191657794',
    projectId: 'kyafeease',
    storageBucket: 'kyafeease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRa0LMnBc1RHkNdMBi8hW8DC1lIJBQb8w',
    appId: '1:876191657794:ios:0d254d002367c3be2ee2db',
    messagingSenderId: '876191657794',
    projectId: 'kyafeease',
    storageBucket: 'kyafeease.appspot.com',
    iosBundleId: 'com.example.kyafeease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMRpa1U3H1jyVGTQ8IMXzPTskL33YzEk',
    appId: '1:876191657794:web:bd93c622df3e68ea2ee2db',
    messagingSenderId: '876191657794',
    projectId: 'kyafeease',
    authDomain: 'kyafeease.firebaseapp.com',
    storageBucket: 'kyafeease.appspot.com',
    measurementId: 'G-9DSVT40CTF',
  );
}
